# Generated by Django 4.2.7 on 2023-12-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitt',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='twitt',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
