# Generated by Django 4.2.7 on 2023-12-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_alter_twitt_created_time_alter_twitt_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitt',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='twitt',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
